[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000


 [[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml_"
  status = 200
  force = true
  conditions = { Language = "en" }

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
